version: "3.9"

services:
  zoom-nginx:
    image: ironex/zoom-nginx:1.0.0
    container_name: docker-magento_nginx
    networks:
      - external
      - internal
      - shared
    user: $GROUP_ID:$USER_ID

networks:
  external:
  internal:
  shared:
    external: true
    name: shared